# Generated by Django 5.0.6 on 2024-08-02 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.ForeignKey(default='default university', on_delete=django.db.models.deletion.CASCADE, to='users.universities'),
        ),
    ]
