# Generated by Django 5.0.6 on 2024-08-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_university'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Student_Response',
        ),
    ]
